In [1]:
import numpy as np
import cv2
import glob
import pandas as pd
import math
import sklearn
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

cuerpo = [cv2.imread(file) for file in glob.glob("jigglypuff/cuerpo*.png")]
ojos = [cv2.imread(file) for file in glob.glob("jigglypuff/ojos*.png")]
orejas = [cv2.imread(file) for file in glob.glob("jigglypuff/orejas*.png")]

Rojo = 0
Azul = 0
Verde = 0
pixelesAzules = 0
pixelesVerdes = 0
pixelesRojos = 0
mediaCuerpo = np.zeros((5,3),dtype=float)

In [2]:
for i in range(len(cuerpo)):
    for filas in range(cuerpo[1].shape[0]):
        for columnas in range(cuerpo[1].shape[1]):
            for color in range(cuerpo[1].shape[2]):
                if color == 0:
                    Azul += cuerpo[i][filas][columnas][color]
                    if cuerpo[i][filas][columnas][color] != 0:
                        pixelesAzules += 1
                if color == 1:
                    Verde += cuerpo[i][filas][columnas][color]
                    if cuerpo[i][filas][columnas][color] != 0:
                        pixelesVerdes += 1
                if color == 2:
                    Rojo += cuerpo[i][filas][columnas][color]
                    if cuerpo[i][filas][columnas][color] != 0:
                        pixelesRojos += 1

    mediaAzul = Azul/pixelesAzules
    mediaVerde = Verde/pixelesVerdes                        
    mediaRojo = Rojo/pixelesRojos
    mediaCuerpo[i][0] = mediaAzul
    mediaCuerpo[i][1] = mediaVerde
    mediaCuerpo[i][2] = mediaRojo
    mediaAzul=0
    mediaVerde=0
    mediaRojo = 0
    pixelesAzules = 0
    pixelesVerdes = 0
    pixelesRojos = 0
    Rojo = 0
    Azul = 0
    Verde = 0

In [3]:
mediaCuerpo

array([[231.60895243, 219.11930604, 252.48161405],
       [183.5449777 , 177.5890674 , 190.09366223],
       [229.23326678, 221.33151414, 246.34956184],
       [220.5143451 , 200.44442416, 219.82981084],
       [200.90454356, 195.16023568, 212.54086725]])

In [4]:
Rojo

0

In [5]:
varianzaCuerpo = np.zeros((5,3),dtype=float)
varAzul = 0.0
varVerde = 0.0
varRojo = 0.0
for i in range(len(cuerpo)):
    for filas in range(cuerpo[1].shape[0]):
        for columnas in range(cuerpo[1].shape[1]):
            for color in range(cuerpo[1].shape[2]):
                if color == 0:
                    if cuerpo[i][filas][columnas][color] != 0:
                        varAzul += pow((cuerpo[i][filas][columnas][color]-mediaCuerpo[i][color]),2)
                        pixelesAzules += 1
                if color == 1:
                    if cuerpo[i][filas][columnas][color] != 0:
                        varVerde += pow((cuerpo[i][filas][columnas][color]-mediaCuerpo[i][color]),2)
                        pixelesVerdes += 1
                if color == 2:
                    if cuerpo[i][filas][columnas][color] != 0:
                        varRojo += pow((cuerpo[i][filas][columnas][color]-mediaCuerpo[i][color]),2)
                        pixelesRojos += 1

    varAzul = varAzul/pixelesAzules
    varVerde = varVerde/pixelesVerdes                        
    varRojo = varRojo/pixelesRojos
    varianzaCuerpo[i][0] = varAzul
    varianzaCuerpo[i][1] = varVerde
    varianzaCuerpo[i][2] = varRojo
    varAzul=0
    varVerde=0
    varRojo = 0
    pixelesAzules = 0
    pixelesVerdes = 0
    pixelesRojos = 0

In [6]:
varianzaCuerpo

array([[ 11.79137125, 189.77674627,   5.2775067 ],
       [ 46.05546916,  86.85880663,  20.63032164],
       [  2.0072505 ,   1.88342061,   1.95917091],
       [ 92.07231665, 131.342447  ,  36.31274807],
       [ 72.38613158, 166.39744001,  82.90605888]])

In [7]:
mediaAzul

0

In [8]:
mediaAzul=0
mediaVerde=0
mediaRojo = 0
mediaOjos = np.zeros((5,3),dtype=float)

In [9]:
mediaOjos = np.zeros((5,3),dtype=float)
for i in range(len(ojos)):
    for filas in range(ojos[1].shape[0]):
        for columnas in range(ojos[1].shape[1]):
            for color in range(ojos[1].shape[2]):
                if color == 0:
                    Azul += ojos[i][filas][columnas][color]
                    if ojos[i][filas][columnas][color] != 0:
                        pixelesAzules += 1
                if color == 1:
                    Verde += ojos[i][filas][columnas][color]
                    if ojos[i][filas][columnas][color] != 0:
                        pixelesVerdes += 1
                if color == 2:
                    Rojo += ojos[i][filas][columnas][color]
                    if ojos[i][filas][columnas][color] != 0:
                        pixelesRojos += 1

    mediaAzul = Azul/pixelesAzules
    mediaVerde = Verde/pixelesVerdes                        
    mediaRojo = Rojo/pixelesRojos
    mediaOjos[i][0] = mediaAzul
    mediaOjos[i][1] = mediaVerde
    mediaOjos[i][2] = mediaRojo
    mediaAzul=0
    mediaVerde=0
    mediaRojo = 0
    pixelesAzules = 0
    pixelesVerdes = 0
    pixelesRojos = 0
    Rojo = 0
    Azul = 0
    Verde = 0

In [10]:
mediaOjos

array([[164.60167159, 180.13158699,  80.18091938],
       [114.69181314,  96.32561664,  70.06837461],
       [134.3496844 , 143.79588819,  65.71228133],
       [162.86266345, 147.84917132,  87.024569  ],
       [138.3481786 , 142.89585474, 105.27018385]])

In [11]:
varianzaOjos = np.zeros((5,3),dtype=float)
varAzul = 0.0
varVerde = 0.0
varRojo = 0.0
pixelesAzules = 0.0
pixelesVerdes = 0.0
pixelesRojos = 0.0
for i in range(len(cuerpo)):
    for filas in range(cuerpo[1].shape[0]):
        for columnas in range(cuerpo[1].shape[1]):
            for color in range(cuerpo[1].shape[2]):
                if color == 0:
                    if cuerpo[i][filas][columnas][color] != 0:
                        varAzul += pow((cuerpo[i][filas][columnas][color]-mediaCuerpo[i][color]),2)
                        pixelesAzules += 1
                if color == 1:
                    if cuerpo[i][filas][columnas][color] != 0:
                        varVerde += pow((cuerpo[i][filas][columnas][color]-mediaCuerpo[i][color]),2)
                        pixelesVerdes += 1
                if color == 2:
                    if cuerpo[i][filas][columnas][color] != 0:
                        varRojo += pow((cuerpo[i][filas][columnas][color]-mediaCuerpo[i][color]),2)
                        pixelesRojos += 1

    varAzul = varAzul/pixelesAzules
    varVerde = varVerde/pixelesVerdes                        
    varRojo = varRojo/pixelesRojos
    varianzaOjos[i][0] = varAzul
    varianzaOjos[i][1] = varVerde
    varianzaOjos[i][2] = varRojo
    varAzul=0
    varVerde=0
    varRojo = 0
    pixelesAzules = 0
    pixelesVerdes = 0
    pixelesRojos = 0

In [12]:
varianzaOjos

array([[ 11.79137125, 189.77674627,   5.2775067 ],
       [ 46.05546916,  86.85880663,  20.63032164],
       [  2.0072505 ,   1.88342061,   1.95917091],
       [ 92.07231665, 131.342447  ,  36.31274807],
       [ 72.38613158, 166.39744001,  82.90605888]])